### ISSUE TITLE
前端风格修改

### ISSUE THREAD

**Issue by lanzhiheng** [HelloJundy/maple#8]
http://www.jack003.com/

参照这里

**Comment by jundihuang** [comment]
- 倒是可以把最新章节 替换成头像
- http://www.jack003.com/ 他头像下面还有一些圈圈的， 可以考虑改成分类
- footer 感觉有点高，且图标跟字都太大了

**Comment by lanzhiheng** [comment]
头像和分类明天可以给个版本。
